### ISSUE TITLE
With windows server ?

### ISSUE THREAD

**Issue by lionnel** [ngsru/atlassian-external-hooks#21]
Hi,

I'm using a stash  v3.9.2 deployed on a windows 8.1 computer.
I've successfully install this add on, and configured it with mirror sample
The script seem to be executed regarding audit log when i push new commit.
If i try the script using git bash, it is well exectuted.
But there is no result when stash execute it.
Any idea ? Has someone already test the add'on under windows instance ?

**Comment by seletskiy** [comment]
I didn't test it on Windows. Are there any information in stash log?

**Comment by lionnel** [comment]
I've a good news ! It work !
It's just that the script has to be a windows shell (.bat or .cmd) and the content has also to be suitable to cmd interpretor.
