### ISSUE TITLE
more env variables

### ISSUE THREAD

**Issue by andreineculau** [ngsru/atlassian-external-hooks#22]
Maybe it's me, but

* the project name (e.g. `STASH_PROJECT_NAME`)
* the base url (e.g. `STASH_BASE_URL` from `com.atlassian.stash.server.getBaseUrl()` ~ `http(s)://stash.example.com`)
* the git url (e.g. `STASH_GIT_URL` ~ `git@stash.example.com:` or `http(s)://stash.example.com/scm/`)

would also have their place as env variables, just like `STASH_REPO_NAME`

**Comment by seletskiy** [comment]
Unfortunately, I don't have time/motivation to do it.

If you ready to make the PR, I will be glad to merge it.

**Comment by andreineculau** [comment]
great! thanks!

On Mon, Sep 21, 2015 at 2:52 PM, Stanislav Seletskiy <
notifications@github.com> wrote:

> Closed #22 <https://github.com/ngsru/atlassian-external-hooks/issues/22>
> via 4e027e3
> <https://github.com/ngsru/atlassian-external-hooks/commit/4e027e37931e722c9dacb665029ab961d1071ac2>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ngsru/atlassian-external-hooks/issues/22#event-414703324>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>
