### ISSUE TITLE
Branch name

### ISSUE THREAD

**Issue by jchannon** [ngsru/atlassian-external-hooks#26]
Does this plugin pass in the branch name into the executable

**Comment by seletskiy** [comment]
@jchannon: Yes. See https://github.com/ngsru/atlassian-external-hooks/wiki/Example.-Test-script for example.

**Comment by jchannon** [comment]
That's great. What I'm trying to do is inspect the branch name and if it's
not in a format then prevent the push. Is that possible?

**Comment by seletskiy** [comment]
@jchannon: Yes, of course. Just return non-zero exit code from the hook.

**Comment by jchannon** [comment]
Brilliant, thanks!
