### ISSUE TITLE
add tag after merge of pull request

### ISSUE THREAD

**Issue by klif** [ngsru/atlassian-external-hooks#36]
I need an algorithm of how to add tag to merge commit of pull request. At the moment we use git commands in the script:
git tag -a "${SOFTWARE_VERSION}" -m "${DESCRIPTION}" ${TO_HASH_COMMIT}

Environment variables are correct and in fact I see new tags in root repository. 

BUT: These new tags don`t synchronized with forks. 
I already tried to talk with attlassian support but they don`t support external tools and aren`t going to response any actions made through it.

There was a mind to add git push --tags to fix add command but this doesn`t work as well.

What is only works is direct clone of root repository - add tag - push it to origin. After such chain new tags really start syncing with forks.

Any ideas?

**Comment by seletskiy** [comment]
It will be possible after #32 will got merged, I guess. Right now I do not see clear way of implementing it.

**Comment by seletskiy** [comment]
@klif: #32 is merged, so it's possible to run arbitrary commands on merge.
