### ISSUE TITLE
Plugin incompatible with Bitbucket 4.6.1

### ISSUE THREAD

**Issue by artditel** [ngsru/atlassian-external-hooks#39]
Hey, I installed Bitbucket 4.6.1 and it says your plugin (3.0-1) should be fixed in order to work. Maybe some api was changed.

**Comment by seletskiy** [comment]
@artditel: I guess it's compatible with 4.6.1, it's just version selector in the marketplace interface which is limiting it. I'll fix it tomorrow.

**Comment by seletskiy** [comment]
3.3-1 version released on marketplace.
