### ISSUE TITLE
Output for post-receive hook

### ISSUE THREAD

**Issue by Shogun147** [ngsru/atlassian-external-hooks#40]
Hi there!

1. In wiki it says that post-receive hook output is silently ignored, but can this be enabled? No examples found.
2. Can post-receive hook to get also stdin? In ideal situation i would like to make this post-receive hook interactive and provide some possible project deployment options.

Is it possible?

Thanks!

**Comment by seletskiy** [comment]
@Shogun147: It's not possible due Bitbucket limitations. Post-receive hooks run asynchronously after push.
